import Head from "next/head";
import PostFeed from "../src/components/post/PostFeed";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextBlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nextjs-boilerplate-logo.png" />
      </Head>
      <div className="grid grid-cols-12">
        <div className="col-span-12 md:col-start-5 md:col-span-4 px-4 md:px-0">
          <PostFeed />
        </div>
      </div>
    </>
  );
}
